### ISSUE TITLE
[ pyAudio Bug ] FATAL: cannot locate cpu MHz in /proc/cpuinfo

### ISSUE THREAD

**Issue by nikhiljohn10** [nikhiljohn10/pi-clap#1]
The following code when executed in RPi which run on Pidora fc20 armv6hl results in a error "**_FATAL: cannot locate cpu MHz in /proc/cpuinfo**_". This error is reflected when the main.py is executed.

``` python
import pyaudio
pa = pyaudio.PyAudio()
```

**Resolution methods tried**
- Installing JACK : Not resolved and some commands of jack also gives same error.

**Comment by eugeniol** [comment]
+1

**Comment by nikhiljohn10** [comment]
Unable to recreated this with the updated versions of pyaudio in armv7 processors on Rasbian.
